# Generated by Django 3.2 on 2021-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type1',
            field=models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_type2',
            field=models.CharField(blank=True, choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback')], max_length=30),
        ),
    ]
