# Generated by Django 3.2 on 2021-08-15 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210814_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_type1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_type2',
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback')], max_length=30, null=True)),
                ('variation_value', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
