# Generated by Django 3.2 on 2021-08-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210815_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_value',
            new_name='variation_value1',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_value2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
