# Generated by Django 3.2.6 on 2021-08-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210824_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/books/%Y/%m/%d/'),
        ),
    ]
