# Generated by Django 3.2.6 on 2021-08-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_photo_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AlterField(
            model_name='book',
            name='photo_main',
            field=models.ImageField(default='default.jpg', upload_to='photos/books/%Y/%m/%d/'),
        ),
    ]
