# Generated by Django 3.2 on 2021-08-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210813_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='book_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
