# Generated by Django 3.2 on 2021-08-15 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_variation_book_type'),
        ('cart', '0004_cart_item_type_of_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='type_of_book',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='type_of_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.variation'),
        ),
    ]
