# Generated by Django 3.2 on 2021-08-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210815_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='book_type',
            field=models.CharField(default='hh', max_length=20),
        ),
    ]
