# Generated by Django 3.2 on 2021-08-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_item_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='type_of_book',
        ),
    ]
